
import edu.odu.cs.cs350.enums.FileType;

public class OtherFile {

    /**
     * string to hold name of the file
     */
    String name;

    /**
     * integer to hold size of the file in kb
     */
    long fileSize;

    /**
     * string to hold local path of this file
     */
    String path;

    
    String typetest;
    FileType fileType;

    /**
    * Get File Name
    @return name
    */

    public String getName() {
        return name;
    }

    /**
    * Set file name function
    @param name
    */

    public void setName(String name) {
        this.name = name;
    }

    /**
    * Get file size function
    @return fileSize
    */

    public long getFileSize() {
        return fileSize;
    }

    /**
    * Set file Size function
    @param fileSize
    */

    public void setFileSize(long fileSize) {
        this.fileSize = fileSize;
    }

    /**
    * Get File path function
    @return path
    */

    public String getPath() {
        return path;
    }

    /**
    * Set file path function
    @param path
    */

    public void setPath(String path) {
        this.path = path;
    }

    /**
    * Get type test function
    @return typetest
    */

    public String getTypetest() {
        return typetest;
    }

    /**
    * Set type test function
    @param typetest
    */

    public void setTypetest(String typetest) {
        this.typetest = typetest;
    }

    /**
    * Get file type function
    @return fileType
    */
    
    public FileType getFileType() {
        return fileType;
    }

    /** 
    * Set file type function
    @param fileType
    */

    public void setFileType(FileType fileType) {
        this.fileType = fileType;
    }

    /**
     * constructor for OtherFile from analysis
     *
     * @param name     string name of file passed by analysis
     * @param id       id # generated by analysis
     * @param typetest string type of file passed by analysis
     * @param fileSize size of file in kb passed by analysis
     * @param path     path of file passed by analysis
     */
    public OtherFile(String name, String typetest, long fileSize, String path, FileType fileType) {
        this.name = name;
        this.typetest = typetest;
        this.fileSize = fileSize;
        this.path = path;
        this.fileType = fileType;

    }
}
