
import edu.odu.cs.cs350.enums.FileType;

public class OtherFile {

    /**
     * string to hold name of the file
     */
    String name;

    /**
     * integer to hold size of the file in kb
     */
    long fileSize;

    /**
     * string to hold local path of this file
     */
    String path;

    
    String typetest;
    FileType fileType;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getFileSize() {
        return fileSize;
    }

    public void setFileSize(long fileSize) {
        this.fileSize = fileSize;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getTypetest() {
        return typetest;
    }

    public void setTypetest(String typetest) {
        this.typetest = typetest;
    }

    public FileType getFileType() {
        return fileType;
    }

    public void setFileType(FileType fileType) {
        this.fileType = fileType;
    }

    /**
     * constructor for OtherFile from analysis
     *
     * @param name     string name of file passed by analysis
     * @param id       id # generated by analysis
     * @param typetest string type of file passed by analysis
     * @param fileSize size of file in kb passed by analysis
     * @param path     path of file passed by analysis
     */
    public OtherFile(String name, String typetest, long fileSize, String path, FileType fileType) {
        this.name = name;
        this.typetest = typetest;
        this.fileSize = fileSize;
        this.path = path;
        this.fileType = fileType;

    }
}
