/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350;

import static org.junit.Assert.*;

class AppTest {
    @Test void App() {
        fail("Not yet implemented");
    }
}
